Mooshak26Dev/Mooshak26/Controllers/AssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mooshak26.Models;
using Mooshak26.Models.Entities;
using Mooshak26.Services;

namespace Mooshak26.Controllers
{
    public class AssignmentsController : Controller
    {
       
        private AssignmentService _service = new AssignmentService();

        // GET: Assignments
        public ActionResult Index(int id)
        {
            if (_service.GetRole() == "Teacher")
            {
                return RedirectToAction("TeachersIndex", new { id = id });
            }
            return View(_service.GetAssignmentsInCourse(id));
        }

        public ActionResult TeachersIndex(int id)
        {
            return View(_service.GetAssignmentsInCourse(id));
        }

        // GET: Assignments/Details/5
        
        public ActionResult Details(int id)
        {
            return View(_service.GetAssignmentDetails(id));
        }

        // GET: Assignments/Create
        
        public ActionResult Create()
        {
            ViewBag.Courses = _service.GetUsersCoursesTitles();
            return View();
        }

        // POST: Assignments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize(Roles = "Teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "assignmentID,courseID,title,description,totalGrade,timeSubmitted,dueDate")] Assignment assignment)
        {
            if (ModelState.IsValid)
            {
                if(_service.CreateAssignment(assignment))
                {
                    return RedirectToAction("Index", new { id = assignment.courseID });
                }
            }

            ViewBag.Courses = _service.GetUsersCoursesTitles();
            return View(assignment);
        }
        
        // GET: Assignments/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_service.GetAssignmentDetails(id));
        }

        // POST: Assignments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize(Roles = "Teacher")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "assignmentID,courseID,title,description,totalGrade,timeSubmitted,dueDate")] Assignment assignment)
        {
            if (ModelState.IsValid)
            {
                if(_service.EditAssignment(assignment))
                {
                    return RedirectToAction("Index", new { id = assignment.courseID });
                }
            }
            return View(assignment);
        }

        // GET: Assignments/Delete/5
        //[Authorize(Roles = "Teacher")]
        public ActionResult Delete(int id)
        {

            Assignment assignment = _service.GetAssignmentDetails(id);
            if (assignment == null)
            {
                return HttpNotFound();
            }
            return View(assignment);
        }

        // POST: Assignments/Delete/5
       // [Authorize(Roles = "Teacher")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Assignment assignment = _service.GetAssignmentDetails(id);
            if (ModelState.IsValid)
            {
                _service.DeleteAssignment(id);
                return RedirectToAction("Index", new { id = assignment.courseID });
            }
            
            
            return View(assignment);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
               // db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mooshak26Dev/Mooshak26/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mooshak26.Models;
using Mooshak26.Models.Entities;
using Mooshak26.Services;
using System.Web.UI.WebControls;

namespace Mooshak26.Controllers
{
    public class CoursesController : Controller
    {
        // private ApplicationDbContext db = new ApplicationDbContext();
        private CourseService _service = new CourseService();
       // private AssignmentsService _assignmentService = new AssignmentsService();

        // GET: Courses
        public ActionResult Index()
        {
         
            var userID = _service.GetUserID();
            if (userID == 0)
            {
                return RedirectToAction("Login", "Account");
            }
            if(_service.GetUserRole() == "Teacher")
            {
                return RedirectToAction("TeacherMainPage");
            }
            else if (_service.GetUserRole() == "Student")
            {
                return RedirectToAction("StudentMainPage");
            }
            else
            {
                return RedirectToAction("AdminMainPage", "Home");
            }       
        }
   
        public ActionResult AdminCourses()
        {
            var userID = _service.GetUserID();
            return View(_service.GetCoursesByUserID(userID));
        }
        public ActionResult TeacherMainPage()
        {
            var userID = _service.GetUserID();
            return View(_service.GetCoursesByUserID(userID));
        }
        public ActionResult StudentMainPage()
        {
            var userID = _service.GetUserID();
            return View(_service.GetCoursesByUserID(userID));
        }

        // GET: Courses/Details/5
        public ActionResult Details(int id)
        {
            
            //Get course details through the CourseService...
            Course course = _service.CourseDetails(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
            /* 
            //Get assignments for each course in Course Details..
            var assignments = _assignmentService.GetAssignmentsInCourse(id);
            return View(assignments);
            */

        }

        // GET: Courses/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,title,description")] Course course)
        {
            if (ModelState.IsValid)
            {
                if (_service.CreateCourse(course))
                {
                    return RedirectToAction("AdminCourses");
                }
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = _service.CourseDetails(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,description")] Course course)
        {
            if (ModelState.IsValid)
            {
                if (_service.EditCourse(course))
                {
                    return RedirectToAction("AdminCourses");
                }
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = _service.CourseDetails(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = _service.CourseDetails(id);
            if (_service.DeleteCourse(course))
            {
                    return RedirectToAction("AdminCourses");   
            }
            //Here should be an error page..
            return HttpNotFound();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mooshak26Dev/Mooshak26/Views/Courses/AdminCourses.cshtml
@model IEnumerable<Mooshak26.Models.Entities.Course>

@{
    ViewBag.Title = "Index";
}

<h2>Admin Mainpage</h2>

<p>
    @Html.ActionLink("Create New Course", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Course
        </th>
        <th>
            Description
        </th>
        <th>
            Actions
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.id })
        </td>
    </tr>
}

</table>
@Html.ActionLink("Go Back", "Index", new { controller = "Courses" }, new { @class = "btn btn-default" })

Mooshak26Dev/Mooshak26/Views/Courses/Create.cshtml
@model Mooshak26.Models.Entities.Course

@{
    ViewBag.Title = "Create";
}

<h2>Create a new Course</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                @Html.ActionLink("Go Back", "AdminCourses", new { controller = "Courses" }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

Mooshak26Dev/Mooshak26/Views/Courses/Delete.cshtml
@model Mooshak26.Models.Entities.Course

@{
    ViewBag.Title = "Delete";
}
<h2> Delete Course</h2>
<h4>Are you sure you want to delete this course?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Go Back", "AdminCourses", new { controller = "Courses" }, new { @class = "btn btn-default" })
        </div>
    }
</div>

Mooshak26Dev/Mooshak26/Views/Courses/Details.cshtml
@model Mooshak26.Models.Entities.Course

@{
    ViewBag.Title = "Details";
}

<h2>Course Details</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
@*
    @model IEnumerable<Mooshak26.Models.Entities.Assignment>

    @{
        ViewBag.Title = "Details";
    }
    <h2>Assignments in Course</h2>
    <!--Checks if the user is a teacher or not-->

    <p>
        @Html.ActionLink("Create New Course", "Create")
    </p>


    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.totalGrade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.timeSubmitted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dueDate)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.totalGrade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.timeSubmitted)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dueDate)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id })
                </td>
            </tr>
        }

    </table>
*@

Mooshak26Dev/Mooshak26/Views/Courses/Edit.cshtml
@model Mooshak26.Models.Entities.Course

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Course</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                @Html.ActionLink("Go Back", "AdminCourses", new { controller = "Courses" }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

Mooshak26Dev/Mooshak26/Views/Courses/Index.cshtml
@model IEnumerable<Mooshak26.Models.Entities.Course>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New Course", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
            @Html.ActionLink("Details", "Details", new { id = item.id }) |
            @Html.ActionLink("See Assignments", "Index", "Assignments", new { id = item.id }, null) |
            @Html.ActionLink("Delete", "Delete", new { id = item.id })
        </td>
    </tr>
}

</table>

Mooshak26Dev/Mooshak26/Views/Courses/StudentMainPage.cshtml
@model IEnumerable<Mooshak26.Models.Entities.Course>
@{
    ViewBag.Title = "Student courses";
}
@using Microsoft.AspNet.Identity
<h2>List of Courses</h2>
<h3> 
    Please choose an action next to a course.
</h3>

<table class="table">
    <tr>
        <th>
           Course
        </th>
        <th>
            Description
        </th>
        <th>
            Actions
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.ActionLink("See Assignments", "Index", "Assignments", new { id = item.id }, null)
            </td>
        </tr>
    }
</table>

Mooshak26Dev/Mooshak26/Views/Courses/TeacherMainPage.cshtml
@model IEnumerable<Mooshak26.Models.Entities.Course>
@{
    ViewBag.Title = "Teachers main page";
}
<h2>List of Courses</h2>
<h3>Please select an action next to each course.</h3>

<table class="table">
    <tr>
        <th>
            Course
        </th>
        <th>
            Description
        </th>
        <th>
            Actions
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.ActionLink("See Assignments", "Index", "Assignments", new { id = item.id }, null)
            </td>
        </tr>
    }
</table>