Mooshak26Dev/Mooshak26/Models/Entities/Milestone.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mooshak26.Models.Entities
{
    /// <summary>
    /// Each assignments will have one or more milestones to represents each part of the assigment to hand in.
    /// For example, one milestone can be "Part 1" of the assignment and another milestone can be "Part 2".
    /// </summary>
    public class Milestone
    {
        /// <summary>
        /// ID represents this specific Milestone and is unique in the DB.
        /// AssignmentID represents what Assignment this milestone is part of.
        /// Title is the title of this milestone.
        /// description does not need to explain..
        /// grade is what precentage this milestone is to the whole assignment.
        /// </summary>
        public int id { get; set; }
        public int assignmentID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int grade { get; set; }
    }
}

Mooshak26Dev/Mooshak26/Models/ViewModels/MilestoneViewModel.cs
using Mooshak26.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mooshak26.Models.ViewModels
{
    public class MilestoneViewModel
    {
        public Milestone milestone { get; set; }
        public HttpPostedFileBase file { get; set; }
    }
}

Mooshak26Dev/Mooshak26/Controllers/MilestonesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mooshak26.Models;
using Mooshak26.Models.Entities;
using Mooshak26.Services;
using System.IO;
using Mooshak26.Models.ViewModels;

namespace Mooshak26.Controllers
{
    public class MilestonesController : Controller
    {
        private MilestoneService _service = new MilestoneService();
        private UserService _us = new UserService();
        private SolutionService _ss = new SolutionService();
        // GET: Milestones
        public ActionResult Index(int id)
        {
            if (_service.GetRole() == "Teacher")
            {
                return RedirectToAction("TeachersIndex", new { id = id });
            }
            return View(_service.GetMilestonesByAssignmentID(id));
        }
        public ActionResult TeachersIndex(int id)
        {
            return View(_service.GetMilestonesByAssignmentID(id));
        }

        //ADD SOLUTION
        public ActionResult mySolutions(int id)
        {
            return View(_service.mySolutions(id));
        }

        // GET: Milestones/Details/5
        public ActionResult Details(int id)
        {
            var milestone1 = _service.GetMilestoneDetails(id);
            MilestoneViewModel temp = new MilestoneViewModel
            {
                milestone = milestone1,
                file = null
            };
            return View(temp);
        }

        [HttpPost]
       // public ActionResult Details(HttpPostedFileBase file)
        public ActionResult Details(MilestoneViewModel milestoneAndFile)
        {
            var userID = _service.GetUserID();
            if (milestoneAndFile.file.ContentLength > 0)
            {
                var FileExtension = Path.GetExtension(milestoneAndFile.file.FileName);
                var fileName = "program" + FileExtension;
                var path = Path.Combine(Server.MapPath("~/App_Data/Submissions"));
                var fullPath = Path.Combine(Server.MapPath("~/App_Data/Submissions"), fileName);

                milestoneAndFile.file.SaveAs(fullPath);
                if(FileExtension == ".py")
                {
                    _service.RunPythonProgram(milestoneAndFile.milestone, path);
                }
                else if(FileExtension == ".cpp")
                {
                    _service.RunCPlusPlusProgram(milestoneAndFile.milestone, path);
                }
               
            }
           
            return RedirectToAction("Feedback", new { id = milestoneAndFile.milestone.id });
        }
        public ActionResult Feedback(int id)
        {
            return View(_service.Feedback(id));
        }

        // GET: Milestones/Create
        public ActionResult Create(int assignmentID)
        {
            ViewBag.Assignments = _service.GetUsersAssignmentTitles(assignmentID);
            return View();
        }

        // POST: Milestones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,assignmentID,title,description,grade")] Milestone milestone)
        {
            if (ModelState.IsValid)
            {
                if(_service.CreateMilestone(milestone))
                {
                    return RedirectToAction("TeachersIndex", new { id = milestone.assignmentID });
                }
            }
            ViewBag.Assignments = _service.GetUsersAssignmentTitles(milestone.assignmentID);
            return View(milestone);
        }

        // GET: Milestones/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_service.GetMilestoneDetails(id));
        }

        // POST: Milestones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,assignmentID,title,description,grade")] Milestone milestone)
        {
            if (ModelState.IsValid)
            {
                if(_service.EditMilestone(milestone))
                {
                    return RedirectToAction("TeachersIndex", new { id = milestone.assignmentID });
                }
            }
            return View(milestone);
        }

        // GET: Milestones/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_service.GetMilestoneDetails(id));
        }

        // POST: Milestones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var assignmentID = _service.GetMilestoneDetails(id).assignmentID;
            _service.DeleteMilestone(id);
            return RedirectToAction("TeachersIndex", new { id = assignmentID });
        }

        public ActionResult ViewSolutionsOf(int id)
        {
            var result = _service.getResults(id);
            return View(result);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mooshak26Dev/Mooshak26/Controllers/SolutionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mooshak26.Models;
using Mooshak26.Models.Entities;
using Mooshak26.Services;

namespace Mooshak26.Controllers
{
    public class SolutionsController : Controller
    {
        private SolutionService _service = new SolutionService();

        // GET: Solutions
        public ActionResult Index(int id)
        {
            return View(_service.GetAllSolutions(id));
        }

        // GET: Solutions/Details/5
        public ActionResult Details(int id)
        {
            return View(_service.GetSolutionDetails(id));
        }

        // GET: Solutions/Create
        public ActionResult Create(int id)
        {
            return View(_service.GetSolutionCreationInfo(id));
        }

        // POST: Solutions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,courseID,assignmentID,milestoneID,input,output")] Solution solution)
        {
            if (ModelState.IsValid)
            {
                if(_service.CreateSolution(solution))
                {
                    return RedirectToAction("Index", new { id = solution.milestoneID });
                }
            }

            return View(solution);
        }

        // GET: Solutions/Edit/5
        public ActionResult Edit(int id)
        { 
            return View(_service.GetSolutionDetails(id));
        }

        // POST: Solutions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,courseID,assignmentID,milestoneID,input,output")] Solution solution)
        {
            if (ModelState.IsValid)
            {
               if(_service.EditSolution(solution))
                {
                    return RedirectToAction("Index", new { id = solution.milestoneID });
                }
            }
            return View(solution);
        }

        public ActionResult Delete(int id)
        {
            Solution sol = _service.GetSolutionDetails(id);
            if (sol == null)
            {
                return HttpNotFound();
            }
            return View(sol);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Solution sol = _service.GetSolutionDetails(id);
            if (_service.DeleteSolution(sol))
            {
                return RedirectToAction("Index", new { id = sol.milestoneID });
            }
            //Here should be an error page..
            return HttpNotFound();
        }



    }
}

Mooshak26Dev/Mooshak26/Views/Milestones/Create.cshtml
@model Mooshak26.Models.Entities.Milestone

@{
    ViewBag.Title = "Create";
}

<h2>Create New Milestone</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.assignmentID, htmlAttributes: new { @class = "control-label col-md-2" })
        @Html.HiddenFor(model => model.assignmentID)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
               @Html.ActionLink("Go Back", "Index", new { controller = "Courses"}, new { @class = "btn btn-default" })

            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Mooshak26Dev/Mooshak26/Views/Milestones/Delete.cshtml
@model Mooshak26.Models.Entities.Milestone

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Milestone</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.assignmentID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.assignmentID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.grade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grade)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Go Back", "Index", new { id = Model.assignmentID }, new { @class = "btn btn-default" })
        </div>
    }
</div>

Mooshak26Dev/Mooshak26/Views/Milestones/Details.cshtml
@model Mooshak26.Models.ViewModels.MilestoneViewModel
    

@{
    ViewBag.Title = "Details";
}
@using (Html.BeginForm("Details", "Milestones", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <br />
    <h2>Details about milestone</h2>
<h4>To turn in your program, press <em>"Choose file"</em> and find the file to submit.</h4>

    <div>
     
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.milestone.assignmentID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.milestone.assignmentID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.milestone.title)
            </dt>
        
            <dd>
                @Html.DisplayFor(model => model.milestone.title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.milestone.description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.milestone.description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.milestone.grade)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.milestone.grade)
            </dd>

        </dl>
    </div>
    <div>
        @Html.HiddenFor(model => model.milestone.assignmentID)
        @Html.HiddenFor(model => model.milestone.id)
        @Html.HiddenFor(model => model.milestone.grade)

        @Html.TextBoxFor(model => model.file, new { type = "file" })
        <br />
        <input type="submit" value="Submit" class="btn btn-default" />
        @Html.ActionLink("Go Back", "Index", new { controller = "Milestones", id = Model.milestone.assignmentID }, new { @class = "btn btn-default" })
     </div>
    <br />

       
}

Mooshak26Dev/Mooshak26/Views/Milestones/Edit.cshtml
@model Mooshak26.Models.Entities.Milestone

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Milestone</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Milestone</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.assignmentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.assignmentID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.assignmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                @Html.ActionLink("Go Back", "Index", new { id = Model.assignmentID }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Mooshak26Dev/Mooshak26/Views/Milestones/Feedback.cshtml
@model IEnumerable<Mooshak26.Models.Entities.SubmittedSolution>
@{
    ViewBag.Title = "Feedback";
}

<h2>Feedback page for submitted solutions</h2>


<table class="table">
    <tr>
        <th>
            Input
        </th>
        <th>
            Expected Output
        </th>
        <th>
            User Output
        </th>
        <th>
            Correct
        </th>
    </tr>
    
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.input)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.expectedOutput)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.output)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.correct)
                </td>
            </tr>
        }
    </table>
    @Html.ActionLink("Go Back", "Index", new { controller = "Milestones", id = Model.ElementAt(0).milestoneID }, new { @class = "btn btn-default" })
    

Mooshak26Dev/Mooshak26/Views/Milestones/Index.cshtml
@model IEnumerable<Mooshak26.Models.Entities.Milestone>

@{
    ViewBag.Title = "Index";
}

<h2>Milestone in Assignment</h2>

<table class="table">
    <tr>
        <th>
            Milestone
        </th>
        <th>
            Description
        </th>
        <th>
            Grade
        </th>
        <th>
            Actions
        </th>
    </tr>

@foreach (var item in Model) {
    @Html.HiddenFor(modelItem => item.assignmentID)
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.grade)
        </td>
        <td>
            @Html.ActionLink("Details/Submit Solution", "Details", new { id=item.id }) |
            @Html.ActionLink("See My Solutions", "mySolutions", new { id=item.id})
        </td>
    </tr>
}

</table>

 @Html.ActionLink("Go Back", "Index", new { controller = "Courses" }, new { @class = "btn btn-default" })
    

Mooshak26Dev/Mooshak26/Views/Milestones/TeachersIndex.cshtml
@model IEnumerable<Mooshak26.Models.Entities.Milestone>

@{
    ViewBag.Title = "Index";
}

<h2>Milestones in Assignment</h2>
<div>
    <table class="table">
        <tr>
            <th>
                Assignment name
            </th>
            <th>
                Description
            </th>
            <th>
                Grade
            </th>
            <th>
                Actions
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.grade)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id }) |
                    @Html.ActionLink("See Solutions", "Index", "Solutions", new { id = item.id }, null) |
                    @Html.ActionLink("Create New Solution", "Create", "Solutions", new { id = item.id }, null) |
                    @Html.ActionLink("See Submissions", "ViewSolutionsOf", new { id = item.id }) 
                </td>
            </tr>
        }

    </table>

    @Html.ActionLink("Go Back", "Index", new { controller = "Courses" }, new { @class = "btn btn-default" })
</div>

Mooshak26Dev/Mooshak26/Views/Milestones/ViewSolutionsOf.cshtml
@model IEnumerable<Mooshak26.Models.Entities.SubmittedSolution>
@{
    ViewBag.Title = "ViewSolutionsOf";
}

<h2>View Student's Solutions </h2>



<table class="table">
    <tr>
        <th>
            Student ID
        </th>
        <th>
            Input
        </th>
        <th>
            Expected Output
        </th>
        <th>
            Student's Output
        </th>
        <th>
            Correct
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.userID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.input)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.expectedOutput)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.output)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.correct)
            </td>
        </tr>
    }
</table>
@Html.ActionLink("Go Back", "Index", new { controller = "Milestones", id = Model.ElementAt(0).milestoneID }, new { @class = "btn btn-default" })

Mooshak26Dev/Mooshak26/Views/Milestones/mySolutions.cshtml
@model IEnumerable<Mooshak26.Models.Entities.SubmittedSolution>
@{
    ViewBag.Title = "mySolutions";
}

<h2>User solutions to milestone</h2>
<h4>Feedback page for submitted solutions</h4>

<table class="table">
    <tr>
        <th>
            Input
        </th>
        <th>
            Expected Output
        </th>
        <th>
            User Output
        </th>
        <th>
            Correct
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.input)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.expectedOutput)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.output)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.correct)
            </td>
        </tr>
    }
</table>
@if (Model.ElementAt(0) != null)
{
    @Html.ActionLink("Go Back", "Index", new { controller = "Milestones", id = Model.ElementAt(0).assignmentID }, new { @class = "btn btn-default" })
}
else
{
    @Html.ActionLink("Go Back", "Index", new { controller = "Courses" }, new { @class = "btn btn-default" })
}